name: Build Action
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Rust
        uses: actions/setup-rust@v1
        with:
          rust-version: stable
      - name: Install Tauri CLI
        run: cargo install tauri-cli
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Build
        run: cargo tauri build
