name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install Rust and System Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y curl libgtk-3-dev libsoup2.4-dev libwebkit2gtk-4.0-dev
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
        source $HOME/.cargo/env
        # Add PKG_CONFIG_PATH environment variable
        export PKG_CONFIG_PATH="/usr/lib/x86_64-linux-gnu/pkgconfig"
    - name: Install additional dependencies
      run: sudo apt-get install -y libwebkit2gtk-4.0-dev
    - name: Add tauri-bundler as a dependency
      run: cargo add tauri-bundler --version "^1.4.8"
    - name: Build
      run: cargo build --verbose
    - name: Build for Windows
      run: cargo tauri build --target=windows
    - name: Build for Android
      run: cargo tauri build --target=android
