name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Rust environment
      uses: actions/setup-rust@v1
      with:
        profile: minimal
        toolchain: stable
    
    - name: Install Tauri CLI
      run: cargo install tauri-cli --version '^1.0.0-beta'
      
    - name: Install Android NDK
      run: |
        wget -O ndk.zip https://dl.google.com/android/repository/android-ndk-r21e-linux-x86_64.zip
        unzip ndk.zip -d $HOME/Android
        echo "export ANDROID_NDK_HOME=$HOME/Android/android-ndk-r21e" >> $HOME/.bashrc
        echo "export PATH=\$PATH:$ANDROID_NDK_HOME" >> $HOME/.bashrc
        source $HOME/.bashrc
    
    - name: Build
      run: cargo build --verbose
      
    - name: Run tests
      run: cargo test --verbose

    - name: Build for Windows
      run: cargo tauri build --target=windows
    
    - name: Build for Android
      run: cargo tauri build --target=android
