name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4  # 升级为支持 Node.js 20 的版本
    - name: Setup Rust
      uses: actions/setup-rust@v1  # 添加设置 Rust 环境的步骤
      with:
        rust-version: 1.56.0  # 设置 Rust 版本
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Build for Windows
      run: cargo tauri build --target=windows
    - name: Build for Android
      run: cargo tauri build --target=android
